# Generated by Django 4.0.2 on 2022-02-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_enrty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrty',
            new_name='Entry',
        ),
    ]
